name: Elevatika
title: Elevatika Enterprises
root: https://CkCreative.github.io/Elev/
permalink: pretty
excerpt_separator: <!--more-->
gems:
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
exclude:
  - Gemfile
  - Gemfile.lock
